[versions]
paperweight = "2.0.0-beta.17" # https://github.com/PaperMC/paperweight
paper = "1.21.6-R0.1-SNAPSHOT" # https://github.com/PaperMC/Paper

## JetBrains
annotations = "24.1.0" # https://github.com/JetBrains/java-annotations
kotlin = "2.1.20" # https://github.com/JetBrains/kotlin

## Kyori
adventure = "4.22.0" # https://github.com/KyoriPowered/adventure

## Minecraft
minecraft = "1.21.6" # https://minecraft.net

## Plugin API
headdatabaseapi = "1.3.1" # https://github.com/Arcaniax-Development/HeadDatabase-API
placeholderapi = "2.11.6" # https://github.com/placeholderapi
itemsadder = "4.0.10" # https://github.com/ItemsAdder
nexo = "1.6.0" # https://github.com/Nexo-MC

## Other
fusion = "1.21.5" # https://github.com/ryderbelserion/Fusion

## Gradle Plugins
fix-javadoc = "1.19" # https://github.com/mfnalex/gradle-fix-javadoc-plugin
run-paper = "2.3.1" # https://github.com/jpenilla/run-task
feather = "0.3.2" # https://github.com/ryderbelserion/Feather
shadow = "9.0.0-beta15" # https://github.com/GradleUp/shadow

[plugins]
# https://github.com/mfnalex/gradle-fix-javadoc-plugin
fix-javadoc = { id = "com.jeff-media.fix-javadoc-plugin", version.ref = "fix-javadoc" }
# https://github.com/ryderbelserion/Feather
feather = { id = "com.ryderbelserion.feather.core", version.ref = "feather" }

[libraries]
# https://github.com/PaperMC/paperweight
paperweight = { module = "io.papermc.paperweight.userdev:io.papermc.paperweight.userdev.gradle.plugin", version.ref = "paperweight" }

# https://github.com/JetBrains/kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
# https://github.com/GradleUp/shadow
shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
# https://fabricmc.net/develop/
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

# https://github.com/JetBrains/java-annotations
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

# https://github.com/Arcaniax-Development/HeadDatabase-API
headdatabaseapi = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabaseapi" }
# https://github.com/placeholderapi
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
# https://github.com/ItemsAdder
itemsadder = { module = "dev.lone:api-itemsadder", version.ref = "itemsadder" }
# https://github.com/Nexo-MC
nexo = { module = "com.nexomc:nexo", version.ref = "nexo" }

# https://github.com/KyoriPowered/adventure
kyori-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }
kyori-logger = { module = "net.kyori:adventure-text-logger-slf4j", version.ref = "adventure" }
kyori-text = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
kyori-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }

# https://github.com/ryderbelserion/Fusion
fusion-paper = { module = "com.ryderbelserion.fusion:fusion-paper", version.ref = "fusion" }
fusion-core = { module = "com.ryderbelserion.fusion:fusion-core", version.ref = "fusion" }

# https://github.com/jpenilla/run-task
run-paper = { module = "xyz.jpenilla:run-task", version.ref = "run-paper" }

[bundles]
adventure = [
    "kyori-legacy",
    "kyori-text",
    "kyori-api"
]

shared = [
    "headdatabaseapi",
    "placeholderapi",
    "itemsadder",
    "nexo"
]

build = [
    "shadow",
    "kotlin"
]

paper = [
    "paperweight",
    "run-paper"
]